const preDefinedLayouts = [
  {
    lg: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 9, minW: 8, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 24, h: 9, minW: 6 },
      { i: 'orderbook', x: 36, y: 0, w: 12, h: 9, minW: 4, minH: 4 },
      { i: 'userInfo', x: 0, y: 9, w: 32, h: 10, minW: 8, minH: 4 },
      { i: 'trade', x: 32, y: 9, w: 16, h: 10, minW: 3, minH: 2 },
    ],
    md: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 6, minW: 12, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 20, h: 6, minW: 8 },
      { i: 'orderbook', x: 32, y: 0, w: 8, h: 6, minW: 8, minH: 4 },
      { i: 'userInfo', x: 0, y: 6, w: 20, h: 10, minW: 16, minH: 4 },
      { i: 'trade', x: 20, y: 6, w: 20, h: 10, minW: 16, minH: 9, maxH: 10 },
    ],
    sm: [
      {
        i: 'pairList',
        x: 0,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 0, w: 24, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 12,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 12,
        w: 24,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 18,
        w: 24,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
    xs: [
      {
        i: 'pairList',
        x: 0,
        y: 0,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 6, w: 16, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 0,
        y: 12,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 18,
        w: 16,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 24,
        w: 16,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
  },
  {
    lg: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 9, minW: 8, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 24, h: 10, minW: 6 },
      { i: 'orderbook', x: 0, y: 9, w: 12, h: 9, minW: 4, minH: 4 },
      { i: 'userInfo', x: 12, y: 10, w: 36, h: 8, minW: 8, minH: 4 },
      { i: 'trade', x: 36, y: 0, w: 12, h: 10, minW: 3, minH: 2 },
    ],
    md: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 6, minW: 12, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 20, h: 6, minW: 8 },
      { i: 'orderbook', x: 32, y: 0, w: 8, h: 6, minW: 8, minH: 4 },
      { i: 'userInfo', x: 0, y: 6, w: 20, h: 10, minW: 16, minH: 4 },
      { i: 'trade', x: 20, y: 6, w: 20, h: 10, minW: 16, minH: 9, maxH: 10 },
    ],
    sm: [
      {
        i: 'pairList',
        x: 0,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 0, w: 24, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 12,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 12,
        w: 24,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 18,
        w: 24,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
    xs: [
      {
        i: 'pairList',
        x: 0,
        y: 0,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 6, w: 16, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 0,
        y: 12,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 18,
        w: 16,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 24,
        w: 16,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
  },
  {
    lg: [
      { i: 'tradingView', w: 24, h: 9, x: 0, y: 0, minW: 6 },
      { i: 'userInfo', w: 32, h: 10, x: 0, y: 9, minW: 8, minH: 4 },
      { i: 'orderbook', w: 12, h: 9, x: 24, y: 0, minW: 4, minH: 4 },
      { i: 'pairList', w: 12, h: 9, x: 36, y: 0, minW: 8, minH: 4 },
      { i: 'trade', w: 16, h: 10, x: 32, y: 9, minW: 3, minH: 2 },
    ],
    md: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 6, minW: 12, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 20, h: 6, minW: 8 },
      { i: 'orderbook', x: 32, y: 0, w: 8, h: 6, minW: 8, minH: 4 },
      { i: 'userInfo', x: 0, y: 6, w: 20, h: 10, minW: 16, minH: 4 },
      { i: 'trade', x: 20, y: 6, w: 20, h: 10, minW: 16, minH: 9, maxH: 10 },
    ],
    sm: [
      {
        i: 'pairList',
        x: 0,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 0, w: 24, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 12,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 12,
        w: 24,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 18,
        w: 24,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
    xs: [
      {
        i: 'pairList',
        x: 0,
        y: 0,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 6, w: 16, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 0,
        y: 12,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 18,
        w: 16,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 24,
        w: 16,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
  },
  {
    lg: [
      { i: 'tradingView', w: 22, h: 11, x: 14, y: 0, minW: 6 },
      { i: 'userInfo', w: 22, h: 8, x: 14, y: 11, minW: 8, minH: 4 },
      { i: 'orderbook', w: 12, h: 19, x: 36, y: 0, minW: 4, minH: 4 },
      { i: 'pairList', w: 14, h: 9, x: 0, y: 0, minW: 8, minH: 4 },
      { i: 'trade', w: 14, h: 10, x: 0, y: 9, minW: 3, minH: 2 },
    ],
    md: [
      { i: 'pairList', x: 0, y: 0, w: 12, h: 6, minW: 12, minH: 4 },
      { i: 'tradingView', x: 12, y: 0, w: 20, h: 6, minW: 8 },
      { i: 'orderbook', x: 32, y: 0, w: 8, h: 6, minW: 8, minH: 4 },
      { i: 'userInfo', x: 0, y: 6, w: 20, h: 10, minW: 16, minH: 4 },
      { i: 'trade', x: 20, y: 6, w: 20, h: 10, minW: 16, minH: 9, maxH: 10 },
    ],
    sm: [
      {
        i: 'pairList',
        x: 0,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 0, w: 24, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 12,
        y: 6,
        w: 12,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 12,
        w: 24,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 18,
        w: 24,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
    xs: [
      {
        i: 'pairList',
        x: 0,
        y: 0,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      { i: 'tradingView', x: 0, y: 6, w: 16, h: 6, minW: 8, static: true },
      {
        i: 'orderbook',
        x: 0,
        y: 12,
        w: 16,
        h: 6,
        minW: 12,
        minH: 4,
        static: true,
      },
      {
        i: 'userInfo',
        x: 0,
        y: 18,
        w: 16,
        h: 6,
        minW: 16,
        minH: 4,
        static: true,
      },
      {
        i: 'trade',
        x: 0,
        y: 24,
        w: 16,
        h: 10,
        minW: 12,
        minH: 9,
        maxH: 10,
        static: true,
      },
    ],
  },
];

export default preDefinedLayouts;
